version: '3.8'

services:
  spark-master:
    image: spark:latest
    platform: linux/amd64
    container_name: spark_master
    network_mode: "host"
    ports:
      - "8088:8088" # Spark Master Web UI
      - "7077:7077" # Spark Master internal port
    environment:
      - SPARK_CONF_DIR=/opt/spark/conf
      - SPARK_MASTER_HOST=node01
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=8088
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
    volumes:
      - ./conf:/opt/spark/conf
      - ./conf/hive-site.xml:/opt/spark/conf/hive-site.xml
      - ./conf/core-site.xml:/opt/spark/conf/core-site.xml
      - ./jars/aws-java-sdk-bundle-1.12.367.jar:/opt/spark/jars/aws-java-sdk-bundle-1.12.367.jar
      - ./jars/iceberg-spark-runtime-4.0_2.13-1.10.0.jar:/opt/spark/jars/iceberg-spark-runtime-4.0_2.13-1.10.0.jar
      - ./jars/iceberg-aws-bundle-1.10.0.jar:/opt/spark/jars/iceberg-aws-bundle-1.10.0.jar
      - ./jars/hadoop-aws-3.3.4.jar:/opt/spark/jars/hadoop-aws-3.3.4.jar
      - ./jars/postgresql-42.7.3.jar:/opt/spark/jars/postgresql-42.7.3.jar
    command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.master.Master"]


  spark-thrift-server:
      image: spark:latest
      platform: linux/amd64
      container_name: spark_thrift
      network_mode: "host"
      depends_on:
        - spark-master
      environment:
        - SPARK_CONF_DIR=/opt/spark/conf
        - SPARK_MASTER_HOST=node01
        - SPARK_MASTER_PORT=7077
        - SPARK_MASTER_WEBUI_PORT=8088
        - AWS_REGION=us-east-1
        - AWS_ACCESS_KEY_ID=minioadmin
        - AWS_SECRET_ACCESS_KEY=minioadmin
        - SPARK_EXTRA_CONF=spark.thriftserver.port=10001      
      volumes:
        - ./conf:/opt/spark/conf
        - ./conf/hive-site.xml:/opt/spark/conf/hive-site.xml
        - ./conf/core-site.xml:/opt/spark/conf/core-site.xml
        - ./jars/aws-java-sdk-bundle-1.12.367.jar:/opt/spark/jars/aws-java-sdk-bundle-1.12.367.jar
        - ./jars/iceberg-spark-runtime-4.0_2.13-1.10.0.jar:/opt/spark/jars/iceberg-spark-runtime-4.0_2.13-1.10.0.jar
        - ./jars/iceberg-aws-bundle-1.10.0.jar:/opt/spark/jars/iceberg-aws-bundle-1.10.0.jar
        - ./jars/hadoop-aws-3.3.4.jar:/opt/spark/jars/hadoop-aws-3.3.4.jar
        - ./jars/postgresql-42.7.3.jar:/opt/spark/jars/postgresql-42.7.3.jar
      command: >
        /opt/spark/bin/spark-submit
        --class org.apache.spark.sql.hive.thriftserver.HiveThriftServer2
        --master spark://node01:7077
        --conf spark.sql.hive.thriftServer.singleSession=true
        --conf spark.thriftserver.port=10001
