version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres_hive
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - data_lake_net
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root"]
      interval: 10s
      timeout: 5s
      retries: 5

  hive-metastore:
    image: apache/hive:4.0.0
    platform: linux/amd64
    container_name: hive_metastore
    ports:
      - "9083:9083"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SERVICE_NAME: metastore
      DB_DRIVER: postgres
      HIVE_CONF: /opt/hive/conf
      HIVE_CONF_DIR: /opt/hive/conf
      SERVICE_OPTS: >
        -Djavax.jdo.option.ConnectionURL=jdbc:postgresql://postgres:5432/metastore
        -Djavax.jdo.option.ConnectionDriverName=org.postgresql.Driver
        -Djavax.jdo.option.ConnectionUserName=hive
        -Djavax.jdo.option.ConnectionPassword=hive
        -Dhive.metastore.uris=thrift://hive-metastore:9083
        -Dhive.metastore.warehouse.dir=s3a://warehouse/
        -Dfs.s3a.endpoint=http://minoproxy:9999
        -Dfs.s3a.access.key=minioadmin
        -Dfs.s3a.secret.key=minioadmin
        -Dfs.s3a.path.style.access=true
        -Dfs.s3a.impl=org.apache.hadoop.fs.s3a.S3AFileSystem
    volumes:
      - /opt/hive/conf/hive-site.xml:/opt/hive/conf/hive-site.xml
      - /opt/hive/conf/core-site.xml:/opt/hive/conf/core-site.xml
      - /opt/hive/jars/postgresql-42.7.3.jar:/opt/hive/lib/postgresql-42.7.3.jar
      - /opt/hive/jars/hadoop-aws-3.3.4.jar:/opt/hive/lib/hadoop-aws-3.3.4.jar
      - /opt/hive/jars/aws-java-sdk-bundle-1.12.367.jar:/opt/hive/lib/aws-java-sdk-bundle-1.12.367.jar
      - /opt/hive/jars/iceberg-api-1.7.0.jar:/opt/hive/lib/iceberg-api-1.7.0.jar
      - /opt/hive/jars/iceberg-aws-1.7.0.jar:/opt/hive/lib/iceberg-aws-1.7.0.jar
      - /opt/hive/jars/iceberg-aws-bundle-1.7.0.jar:/opt/hive/lib/iceberg-aws-bundle-1.7.0.jar
      - /opt/hive/jars/iceberg-common-1.7.0.jar:/opt/hive/lib/iceberg-common-1.7.0.jar
      - /opt/hive/jars/iceberg-core-1.7.0.jar:/opt/hive/lib/iceberg-core-1.7.0.jar
      - /opt/hive/jars/iceberg-hive-metastore-1.7.0.jar:/opt/hive/lib/iceberg-hive-metastore-1.7.0.jar
      - /opt/hive/jars/iceberg-hive-runtime-1.7.0.jar:/opt/hive/lib/iceberg-hive-runtime-1.7.0.jar
      - /opt/hive/jars/iceberg-orc-1.7.0:/opt/hive/lib/iceberg-orc-1.7.0  
      - /opt/hive/jars/iceberg-parquet-1.7.0.jar:/opt/hive/lib/iceberg-parquet-1.7.0.jar       
      - /opt/hive/hive_home:/home/hive
    networks:
      - data_lake_net
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9083 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 180s

  hive-server2:
    image: apache/hive:4.0.0
    platform: linux/amd64
    container_name: hive_server2
    ports:
      - "10000:10000"
    depends_on:
      postgres:
        condition: service_healthy      
    environment:
      SERVICE_NAME: hiveserver2
      DB_DRIVER: postgres
      HIVE_CONF: /opt/hive/conf
      HIVE_CONF_DIR: /opt/hive/conf      
      SERVICE_OPTS: >
        -Djavax.jdo.option.ConnectionURL=jdbc:postgresql://postgres:5432/metastore
        -Djavax.jdo.option.ConnectionDriverName=org.postgresql.Driver
        -Djavax.jdo.option.ConnectionUserName=hive
        -Djavax.jdo.option.ConnectionPassword=hive
        -Dhive.metastore.uris=thrift://hive-metastore:9083
        -Dhive.metastore.warehouse.dir=s3a://warehouse/
        -Dfs.s3a.endpoint=http://minoproxy:9999
        -Dfs.s3a.access.key=minioadmin
        -Dfs.s3a.secret.key=minioadmin
        -Dfs.s3a.path.style.access=true
        -Dfs.s3a.impl=org.apache.hadoop.fs.s3a.S3AFileSystem
    volumes:
      - /opt/hive/conf/hive-site.xml:/opt/hive/conf/hive-site.xml
      - /opt/hive/conf/core-site.xml:/opt/hive/conf/core-site.xml
      - /opt/hive/jars/postgresql-42.7.3.jar:/opt/hive/lib/postgresql-42.7.3.jar
      - /opt/hive/jars/hadoop-aws-3.3.4.jar:/opt/hive/lib/hadoop-aws-3.3.4.jar
      - /opt/hive/jars/aws-java-sdk-bundle-1.12.367.jar:/opt/hive/lib/aws-java-sdk-bundle-1.12.367.jar
      - /opt/hive/jars/iceberg-api-1.7.0.jar:/opt/hive/lib/iceberg-api-1.7.0.jar
      - /opt/hive/jars/iceberg-aws-1.7.0.jar:/opt/hive/lib/iceberg-aws-1.7.0.jar
      - /opt/hive/jars/iceberg-aws-bundle-1.7.0.jar:/opt/hive/lib/iceberg-aws-bundle-1.7.0.jar
      - /opt/hive/jars/iceberg-common-1.7.0.jar:/opt/hive/lib/iceberg-common-1.7.0.jar
      - /opt/hive/jars/iceberg-core-1.7.0.jar:/opt/hive/lib/iceberg-core-1.7.0.jar
      - /opt/hive/jars/iceberg-hive-metastore-1.7.0.jar:/opt/hive/lib/iceberg-hive-metastore-1.7.0.jar
      - /opt/hive/jars/iceberg-hive-runtime-1.7.0.jar:/opt/hive/lib/iceberg-hive-runtime-1.7.0.jar
      - /opt/hive/jars/iceberg-orc-1.7.0:/opt/hive/lib/iceberg-orc-1.7.0  
      - /opt/hive/jars/iceberg-parquet-1.7.0.jar:/opt/hive/lib/iceberg-parquet-1.7.0.jar       
      - /opt/hive/hive_home:/home/hive
    networks:
      - data_lake_net
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 10000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 180s

  hue:
    image: gethue/hue:latest
    container_name: hue
    platform: linux/amd64
    ports:
      - "8888:8888"
    networks:
      - data_lake_net
    environment:
      - HUE_CONF_DIR=/usr/share/hue/desktop/conf
    volumes:
      - /opt/hue/conf/hue.ini:/usr/share/hue/desktop/conf/hue.ini
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 8888 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 180s

networks:
  data_lake_net:
    driver: bridge
    name: hive_minio_net

volumes:
  postgres_data:
    name: hive_postgres_data
